### ISSUE TITLE
fields with enum type in models

### ISSUE THREAD

**Issue by ahmad1394** [VestaRayanAfzar/vesta#1]
when generate a controller in client side it should add a private variable in `exampleController`  class that is equal to imported `enum` from `exampleModel.ts` but it doesn't.
for example below lines should add into `voucherController.ts` file
`import {VoucherCurrency} from "../../cmn/models/Voucher";`
`private Currency = VoucherCurrency;`

**Comment by ghost** [comment]
When you use an `enum` from another model, code generator doesn't know the import path. however, it gives you a warning on command line to import it yourself.
